import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Firsttopbar from "./components/Firsttopbar";
import SecTopbar from "./components/SecTopbar";
import Navbar from "./components/Navbar3";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className} >

<Firsttopbar/>
<SecTopbar/>
<Navbar/>

        <main>
        {children}
        </main>

        </body>
    </html>
  );
}
